export const dataMarcas = [
    {
        value : "",
        label : "Marca",
    },    
    {
        value:"4",
        label:"MCLAREN",
    },
    {
        value:"5",
        label:"ALFA ROMEO",
    },
    {
        value:"6",
        label:"ASIA MOTORS",
    },
    {
        value:"7",
        label:"AUDI",
    },
    {
        value:"8",
        label:"BMW",
    },
    {
        value:"9",
        label:"BUGGY",
    },
    {
        value:"10",
        label:"BUGRE",
    },
    {
        value:"11",
        label:"CHERY",
    },
    {
        value:"12",
        label:"CADILLAC",
    },
    {
        value:"13",
        label:"CHRYSLER",
    },
    {
        value:"14",
        label:"CITROEN",
    },
    {
        value:"15",
        label:"DODGE",
    },
    {
        value:"16",
        label:"FERRARI",
    },
    {
        value:"17",
        label:"FIAT",
    },
    {
        value:"18",
        label:"FORD",
    },
    {
        value:"19",
        label:"GM-CHEVROLET",
    },
    {
        value:"20",
        label:"GURGEL",
    },
    {
        value:"21",
        label:"HONDA",
    },
    {
        value:"22",
        label:"HYUNDAI",
    },
    {
        value:"23",
        label:"JAC",
    },
    {
        value:"24",
        label:"JAGUAR",
    },
    {
        value:"25",
        label:"JEEP",
    },
    {
        value:"26",
        label:"KIA MOTORS",
    },
    {
        value:"27",
        label:"LAMBORGHINI",
    },
    {
        value:"28",
        label:"LAND ROVER",
    },
    {
        value:"29",
        label:"MAZDA",
    },
    {
        value:"30",
        label:"MERCEDES-BENZ",
    },
    {
        value:"31",
        label:"MITSUBISHI",
    },
    {
        value:"32",
        label:"NISSAN",
    },
    {
        value:"33",
        label:"PEUGEOT",
    },
    {
        value:"34",
        label:"PORSCHE",
    },
    {
        value:"35",
        label:"RENAULT",
    },
    {
        value:"36",
        label:"ROVER",
    },
    {
        value:"37",
        label:"SUZUKI",
    },
    {
        value:"38",
        label:"TAC",
    },
    {
        value:"39",
        label:"TOYOTA",
    },
    {
        value:"40",
        label:"TROLLER",
    },
    {
        value:"41",
        label:"VW-VOLKSWAGEN",
    },
    {
        value:"42",
        label:"VOLVO",
    },
    {
        value:"43",
        label:"SMART",
    },
    {
        value:"44",
        label:"SHINERAY",
    },
    {
        value:"45",
        label:"ROLLS-ROYCE",
    },
    {
        value:"46",
        label:"PUMA",
    },
    {
        value:"47",
        label:"TESLA",
    },
    {
        value:"48",
        label:"IVECO",
    },
];